[package]
name = "jpeg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jpeg-sys = { path = "../jpeg-sys" }
common = { path = "../../common" }